name: Create the release

on:
  push:
    branches: 
      - main

jobs:
  test_unit:
    uses: ./.github/workflows/unitTestJob.yml

  release_tag:
    needs: test_unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      # - name: Configure git
      #     run: git config user.email ${GIT_CI_EMAIL}      
      #     run: git config user.name ${GIT_CI_USER}      
      - name: Create the release      
        run: npm ci
        run: npm run release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push the release
        run: git push --follow-tags
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
