name: Create the release

on:
  push:
    branches: 
      - main

jobs:
  # test_unit:
  #   uses: ./.github/workflows/unitTestJob.yml

  release_tag:
    # needs: test_unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Configure git
        run: | 
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"     
      - name: Create the release      
        run: |
          npm ci
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push the release
        run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
